apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-starter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-starter
  template:
    metadata:
      labels:
        app: devops-starter
    spec:
      containers:
      - name: devops-starter
        image: your-dockerhub-user/devops-starter:latest
        ports:
        - containerPort: 5000
